spring.application.name=FlashLearn
spring.datasource.url=jdbc:mysql://localhost:3306/flashlearn
spring.datasource.username=root
spring.datasource.password=Sgh21Qp8rta+/
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=yourSuperSecretKeyThatShouldBeLongEnough12345
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malets.artyom10@gmail.com
spring.mail.password=ktsy ngxg mjre ncgi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from-name=FlashLearn
app.auth.verification-url-prefix=http://localhost:8080/api/auth/confirm?token=

supabase.project-id=zeoqvmosfbzlxqbxyggp
supabase.s3.endpoint=https://zeoqvmosfbzlxqbxyggp.storage.supabase.co/storage/v1/s3
supabase.s3.region=eu-north-1
supabase.s3.access-key=90f54366ef3b61dcf668fa5eb98b97c7
supabase.s3.secret-key=9a86fcc107adc1b8b7cd5ac586ece5985c15fd2f6ea25e2e135d996bee61d776
supabase.s3.avatars-bucket=avatars
supabase.s3.landing-page-bucket=landing-page

